lines = [
    "name: 브리핑룸 자동 수집\n",
    "\n",
    "on:\n",
    "  schedule:\n",
    "    - cron: '0 9 * * 1-5'   # 월~금 오후 6시 KST\n",
    "    - cron: '0 16 * * 6'    # 토요일 새벽 1시 KST\n",
    "    - cron: '0 16 * * 0'    # 일요일 새벽 1시 KST\n",
    "  workflow_dispatch:\n",
    "    inputs:\n",
    "      mode:\n",
    "        description: 'daily 또는 weekly'\n",
    "        required: false\n",
    "        default: 'auto'\n",
    "      date:\n",
    "        description: '날짜 (YYYY-MM-DD)'\n",
    "        required: false\n",
    "\n",
    "permissions:\n",
    "  contents: write\n",
    "\n",
    "jobs:\n",
    "  briefing:\n",
    "    runs-on: ubuntu-latest\n",
    "    timeout-minutes: 120\n",
    "\n",
    "    steps:\n",
    "      - name: 저장소 체크아웃\n",
    "        uses: actions/checkout@v4\n",
    "        with:\n",
]
dollar = chr(36)
lines += [
    f"          token: {dollar}{{{{ secrets.GITHUB_TOKEN }}}}\n",
    "\n",
    "      - name: Python 설치\n",
    "        uses: actions/setup-python@v5\n",
    "        with:\n",
    "          python-version: '3.11'\n",
    "\n",
    "      - name: 패키지 설치\n",
    "        run: |\n",
    "          pip install -r requirements.txt\n",
    "          playwright install chromium\n",
    "          playwright install-deps chromium\n",
    "\n",
    "      - name: 브리핑룸 실행\n",
    "        env:\n",
    f"          WP_USER: {dollar}{{{{ secrets.WP_USER }}}}\n",
    f"          WP_PASS: {dollar}{{{{ secrets.WP_PASS }}}}\n",
    f"          RUN_MODE: {dollar}{{{{ github.event.inputs.mode || 'auto' }}}}\n",
    f"          RUN_DATE: {dollar}{{{{ github.event.inputs.date || '' }}}}\n",
    "        run: python briefing.py\n",
    "\n",
    "      - name: 결과 커밋 및 푸시\n",
    "        run: |\n",
    "          git config user.name \"briefing-bot\"\n",
    "          git config user.email \"bot@briefingroom.kr\"\n",
    "          git add -A\n",
    "          git diff --staged --quiet || git commit -m \"자동 수집: \"\n",
    "          git push\n",
]
import os
os.makedirs('.github/workflows', exist_ok=True)
with open('.github/workflows/briefing.yml', 'w', encoding='utf-8') as f:
    f.writelines(lines)
print('완료')
